openapi: 3.0.0
info:
  title: Audit API
  description: This API provides audit info.
  contact:
    email: ryancho.hakhyeon@gmail.com
  version: 1.0.0

paths:
  /crawling-image:
    get:
      tags:
        - devices
      summary: gets new results of image crawling
      description: Gets a list of image crawlings added after a timestamp
      operationId: app.get_crawling_image_reading
      parameters:
        - name: index
          in : query
          description: Gets the Crawling Image at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200' :
          description: Successfully returned a image crawling event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ListofImageCrawling'
        '400' :
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404' :
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /list-category:
    get:
      tags:
        - devices
      summary: gets new results of image category
      description: Gets a list of image categories added after a timestamp
      operationId: app.get_list_category_reading
      parameters:
        - name: index
          in: query
          description: Gets the Category List at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a list category event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ListofImageCategory'
        '400' :
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404' :
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    ListofImageCrawling:
      required:
      - image_id
      - image_name
      - date_created
      - features
      type: object
      properties:
        image_id:
          type: string
          example: "L_001"
        image_name:
          type: string
          example: car
        date_created:
          type: string
          format: date-time
        features:
          $ref: '#/components/schemas/ListFeature'
    ListofImageCategory:
      required:
      - category_id
      - category_name
      - images_num
      - date_created
      type: object
      properties:
        category_id:
          type: string
          example: "C_001"
        category_name:
          type: string
          example: vehicle
        images_num:
          type: integer
          example: 100
        date_created:
          type: string
          format: date-time
    ListFeature:
      required:
      - dir_path
      - dir_size
      type: object
      properties:
        dir_path:
          type: string
          example: c:/user/usr
        dir_size:
          type: string
          example: "1 MB"
