openapi: 3.0.0
info:
  title: Image Crawling API
  description: This is a simple API that makes sure image crawling.
  contact:
    email: ryancho.hakhyeon@gmail.com
  version: 1.0.0
tags:
  - name: devices
    description: Available to get several images from Internet.
paths:
  /crawling-image:
    get:
      tags:
        - devices
      summary: gets new results of image crawling
      description: Gets a list of image crawlings added after a timestamp
      operationId: app.get_crawling_image
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-02-17T09:30:33.001z
        - name: end_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-02-17T09:30:33.001z
      responses:
        '200' :
          description: Successfully returned a list of image crawling
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ListofImageCrawling'
        '400' :
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /list-category:
    get:
      tags:
        - devices
      summary: gets new results of image category
      description: Gets a list of image categories added after a timestamp
      operationId: app.get_list_category
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-02-17T09:30:33.001z
        - name: end_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-02-17T09:30:33.001z
      responses:
        '200':
          description: Successfully returned a list of image crawling
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ListofImageCategory'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    ListofImageCrawling:
      required:
      - image_id
      - image_name
      - timestamp
      - features
      type: object
      properties:
        image_id:
          type: string
          example: "L_001"
        image_name:
          type: string
          example: car
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        features:
          $ref: '#/components/schemas/ListFeature'
    ListofImageCategory:
      required:
      - category_id
      - category_name
      - images_num
      - timestamp
      type: object
      properties:
        category_id:
          type: string
          example: "C_001"
        category_name:
          type: string
          example: vehicle
        images_num:
          type: integer
          example: 100
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    ListFeature:
      required:
      - dir_path
      - dir_size
      type: object
      properties:
        dir_path:
          type: string
          example: c:/user/usr
        dir_size:
          type: string
          example: "1 MB"
